### ISSUE TITLE
issue running CLI for SCEDC on AWS

### ISSUE THREAD

**Issue by mdenolle** [mdenolle/NoisePy#191]
Ran into this bug:

```(noisepy) [ec2-user@ip-172-31-28-161 ~]$ ls
Miniconda3-latest-Linux-x86_64.sh  miniconda
(noisepy) [ec2-user@ip-172-31-28-161 ~]$ vi run_noisepy.sh
(noisepy) [ec2-user@ip-172-31-28-161 ~]$ aws s3 ls s3://scoped-noise
2023-09-09 18:59:00       1096 test.jl
(noisepy) [ec2-user@ip-172-31-28-161 ~]$ aws s3api put-object --bucket scoped-noise  --key marine-ccf --content-length 0

An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
(noisepy) [ec2-user@ip-172-31-28-161 ~]$ noisepy cross_correlate --format zarr --raw_data_path s3://scedc-pds/continuous_waveforms/ \
--xml_path s3://scedc-pds/FDSNstationXML/CI/ \
--ccf_path s3://scoped-noise/marine-ccf \
--stations=SBC,RIO,DEV \
--start=2022-02-02 \
--end=2022-02-03
Traceback (most recent call last):
  File "/home/ec2-user/miniconda/envs/noisepy/bin/noisepy", line 5, in <module>
    from noisepy.seis import main
  File "/home/ec2-user/miniconda/envs/noisepy/lib/python3.10/site-packages/noisepy/seis/__init__.py", line 5, in <module>
    from .S0A_download_ASDF_MPI import download  # noqa: F401
  File "/home/ec2-user/miniconda/envs/noisepy/lib/python3.10/site-packages/noisepy/seis/S0A_download_ASDF_MPI.py", line 18, in <module>
    from noisepy.seis.datatypes import ConfigParameters
  File "/home/ec2-user/miniconda/envs/noisepy/lib/python3.10/site-packages/noisepy/seis/datatypes.py", line 112, in <module>
    class ConfigParameters(BaseModel):
  File "/home/ec2-user/miniconda/envs/noisepy/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 171, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/home/ec2-user/miniconda/envs/noisepy/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 361, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "/home/ec2-user/miniconda/envs/noisepy/lib/python3.10/site-packages/pydantic/_internal/_fields.py", line 96, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "/home/ec2-user/miniconda/envs/noisepy/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 212, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "/home/ec2-user/miniconda/envs/noisepy/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 221, in eval_type_lenient
    value = _make_forward_ref(value, is_argument=False, is_class=True)
TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'
(noisepy) [ec2-user@ip-172-31-28-161 ~]$ ls
Miniconda3-latest-Linux-x86_64.sh  miniconda  run_noisepy.sh
(noisepy) [ec2-user@ip-172-31-28-161 ~]$ aws s3 cp run_noisepy.sh s3://scoped-noise
upload failed: ./run_noisepy.sh to s3://scoped-noise/run_noisepy.sh An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
(noisepy) [ec2-user@ip-172-31-28-161 ~]$ 
```

I attached a role to the instance called SCOPED, which has the carlosgjs-noisepy permission policy. 

I think there are two issues there: 1) we need to write a policy that has PutObject for any SCOPED roles, and 2) there seems to be an issue on EC2 that we did not encounter on local.

**Comment by niyiyu** [comment]
For the record:

1) we are missing the policy that allows a specific role to write to S3 bucket. The policy is listed below and shall be manually added in the bucket setting.
```
{
    "Version": "2012-10-17",
    "Id": "Policy1674832359797",
    "Statement": [
        {
            "Sid": "Stmt1674832357905",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::073795725844:role/SCOPED"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::scoped-noise/*"
        }
    ]
}
```

2) Seems there is some version problem with pydantic==2.0.0 with python 3.10. Error reported as 
```
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/noisepy/bin/noisepy", line 5, in <module>
    from noisepy.seis import main
  File "/home/ec2-user/miniconda3/envs/noisepy/lib/python3.10/site-packages/noisepy/seis/__init__.py", line 5, in <module>
    from .S0A_download_ASDF_MPI import download  # noqa: F401
  File "/home/ec2-user/miniconda3/envs/noisepy/lib/python3.10/site-packages/noisepy/seis/S0A_download_ASDF_MPI.py", line 18, in <module>
    from noisepy.seis.datatypes import ConfigParameters
  File "/home/ec2-user/miniconda3/envs/noisepy/lib/python3.10/site-packages/noisepy/seis/datatypes.py", line 112, in <module>
    class ConfigParameters(BaseModel):
  File "/home/ec2-user/miniconda3/envs/noisepy/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 171, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/home/ec2-user/miniconda3/envs/noisepy/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 361, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "/home/ec2-user/miniconda3/envs/noisepy/lib/python3.10/site-packages/pydantic/_internal/_fields.py", line 96, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "/home/ec2-user/miniconda3/envs/noisepy/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 212, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "/home/ec2-user/miniconda3/envs/noisepy/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 221, in eval_type_lenient
    value = _make_forward_ref(value, is_argument=False, is_class=True)
TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'
```

upgrading pydantic to 2.3.0 fix this under python 3.10. 
pydantic 2.0.0 also works with python 3.9

**Comment by mdenolle** [comment]
@niyiyu fixed everything
